// FICHIER GENERE - ne pas modifier a la main.
// Source : Docs_Implementation/annexes/code/ (verifie contre nestest.log).

/// Mode d'adressage (annexe A).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Mode {
    Imp,
    Acc,
    Imm,
    Zp0,
    Zpx,
    Zpy,
    Abs,
    Abx,
    Aby,
    Ind,
    Izx,
    Izy,
    Rel,
}

impl Mode {
    /// Nombre d'octets d'operande apres l'opcode.
    pub const fn operand_len(self) -> u8 {
        match self {
            Mode::Imp | Mode::Acc => 0,
            Mode::Imm | Mode::Zp0 | Mode::Zpx | Mode::Zpy | Mode::Izx | Mode::Izy | Mode::Rel => 1,
            Mode::Abs | Mode::Abx | Mode::Aby | Mode::Ind => 2,
        }
    }
}

/// Informations de desassemblage / verification. N'intervient JAMAIS dans le sequencement.
#[derive(Clone, Copy, Debug)]
pub struct OpInfo {
    pub mnemonic: &'static str,
    pub mode: Mode,
    /// Cycles de base (0 pour JAM).
    pub cycles: u8,
    /// 0, 1 (+1 si changement de page, lectures) ou 2 (branchement).
    pub page_penalty: u8,
    pub official: bool,
}

const fn op(
    mnemonic: &'static str,
    mode: Mode,
    cycles: u8,
    page_penalty: u8,
    official: bool,
) -> OpInfo {
    OpInfo {
        mnemonic,
        mode,
        cycles,
        page_penalty,
        official,
    }
}

pub static OPCODES: [OpInfo; 256] = [
    /* 00 */ op("BRK", Mode::Imp, 7, 0, true),
    /* 01 */ op("ORA", Mode::Izx, 6, 0, true),
    /* 02 */ op("JAM", Mode::Imp, 0, 0, false),
    /* 03 */ op("SLO", Mode::Izx, 8, 0, false),
    /* 04 */ op("NOP", Mode::Zp0, 3, 0, false),
    /* 05 */ op("ORA", Mode::Zp0, 3, 0, true),
    /* 06 */ op("ASL", Mode::Zp0, 5, 0, true),
    /* 07 */ op("SLO", Mode::Zp0, 5, 0, false),
    /* 08 */ op("PHP", Mode::Imp, 3, 0, true),
    /* 09 */ op("ORA", Mode::Imm, 2, 0, true),
    /* 0A */ op("ASL", Mode::Acc, 2, 0, true),
    /* 0B */ op("ANC", Mode::Imm, 2, 0, false),
    /* 0C */ op("NOP", Mode::Abs, 4, 0, false),
    /* 0D */ op("ORA", Mode::Abs, 4, 0, true),
    /* 0E */ op("ASL", Mode::Abs, 6, 0, true),
    /* 0F */ op("SLO", Mode::Abs, 6, 0, false),
    /* 10 */ op("BPL", Mode::Rel, 2, 2, true),
    /* 11 */ op("ORA", Mode::Izy, 5, 1, true),
    /* 12 */ op("JAM", Mode::Imp, 0, 0, false),
    /* 13 */ op("SLO", Mode::Izy, 8, 0, false),
    /* 14 */ op("NOP", Mode::Zpx, 4, 0, false),
    /* 15 */ op("ORA", Mode::Zpx, 4, 0, true),
    /* 16 */ op("ASL", Mode::Zpx, 6, 0, true),
    /* 17 */ op("SLO", Mode::Zpx, 6, 0, false),
    /* 18 */ op("CLC", Mode::Imp, 2, 0, true),
    /* 19 */ op("ORA", Mode::Aby, 4, 1, true),
    /* 1A */ op("NOP", Mode::Imp, 2, 0, false),
    /* 1B */ op("SLO", Mode::Aby, 7, 0, false),
    /* 1C */ op("NOP", Mode::Abx, 4, 1, false),
    /* 1D */ op("ORA", Mode::Abx, 4, 1, true),
    /* 1E */ op("ASL", Mode::Abx, 7, 0, true),
    /* 1F */ op("SLO", Mode::Abx, 7, 0, false),
    /* 20 */ op("JSR", Mode::Abs, 6, 0, true),
    /* 21 */ op("AND", Mode::Izx, 6, 0, true),
    /* 22 */ op("JAM", Mode::Imp, 0, 0, false),
    /* 23 */ op("RLA", Mode::Izx, 8, 0, false),
    /* 24 */ op("BIT", Mode::Zp0, 3, 0, true),
    /* 25 */ op("AND", Mode::Zp0, 3, 0, true),
    /* 26 */ op("ROL", Mode::Zp0, 5, 0, true),
    /* 27 */ op("RLA", Mode::Zp0, 5, 0, false),
    /* 28 */ op("PLP", Mode::Imp, 4, 0, true),
    /* 29 */ op("AND", Mode::Imm, 2, 0, true),
    /* 2A */ op("ROL", Mode::Acc, 2, 0, true),
    /* 2B */ op("ANC", Mode::Imm, 2, 0, false),
    /* 2C */ op("BIT", Mode::Abs, 4, 0, true),
    /* 2D */ op("AND", Mode::Abs, 4, 0, true),
    /* 2E */ op("ROL", Mode::Abs, 6, 0, true),
    /* 2F */ op("RLA", Mode::Abs, 6, 0, false),
    /* 30 */ op("BMI", Mode::Rel, 2, 2, true),
    /* 31 */ op("AND", Mode::Izy, 5, 1, true),
    /* 32 */ op("JAM", Mode::Imp, 0, 0, false),
    /* 33 */ op("RLA", Mode::Izy, 8, 0, false),
    /* 34 */ op("NOP", Mode::Zpx, 4, 0, false),
    /* 35 */ op("AND", Mode::Zpx, 4, 0, true),
    /* 36 */ op("ROL", Mode::Zpx, 6, 0, true),
    /* 37 */ op("RLA", Mode::Zpx, 6, 0, false),
    /* 38 */ op("SEC", Mode::Imp, 2, 0, true),
    /* 39 */ op("AND", Mode::Aby, 4, 1, true),
    /* 3A */ op("NOP", Mode::Imp, 2, 0, false),
    /* 3B */ op("RLA", Mode::Aby, 7, 0, false),
    /* 3C */ op("NOP", Mode::Abx, 4, 1, false),
    /* 3D */ op("AND", Mode::Abx, 4, 1, true),
    /* 3E */ op("ROL", Mode::Abx, 7, 0, true),
    /* 3F */ op("RLA", Mode::Abx, 7, 0, false),
    /* 40 */ op("RTI", Mode::Imp, 6, 0, true),
    /* 41 */ op("EOR", Mode::Izx, 6, 0, true),
    /* 42 */ op("JAM", Mode::Imp, 0, 0, false),
    /* 43 */ op("SRE", Mode::Izx, 8, 0, false),
    /* 44 */ op("NOP", Mode::Zp0, 3, 0, false),
    /* 45 */ op("EOR", Mode::Zp0, 3, 0, true),
    /* 46 */ op("LSR", Mode::Zp0, 5, 0, true),
    /* 47 */ op("SRE", Mode::Zp0, 5, 0, false),
    /* 48 */ op("PHA", Mode::Imp, 3, 0, true),
    /* 49 */ op("EOR", Mode::Imm, 2, 0, true),
    /* 4A */ op("LSR", Mode::Acc, 2, 0, true),
    /* 4B */ op("ALR", Mode::Imm, 2, 0, false),
    /* 4C */ op("JMP", Mode::Abs, 3, 0, true),
    /* 4D */ op("EOR", Mode::Abs, 4, 0, true),
    /* 4E */ op("LSR", Mode::Abs, 6, 0, true),
    /* 4F */ op("SRE", Mode::Abs, 6, 0, false),
    /* 50 */ op("BVC", Mode::Rel, 2, 2, true),
    /* 51 */ op("EOR", Mode::Izy, 5, 1, true),
    /* 52 */ op("JAM", Mode::Imp, 0, 0, false),
    /* 53 */ op("SRE", Mode::Izy, 8, 0, false),
    /* 54 */ op("NOP", Mode::Zpx, 4, 0, false),
    /* 55 */ op("EOR", Mode::Zpx, 4, 0, true),
    /* 56 */ op("LSR", Mode::Zpx, 6, 0, true),
    /* 57 */ op("SRE", Mode::Zpx, 6, 0, false),
    /* 58 */ op("CLI", Mode::Imp, 2, 0, true),
    /* 59 */ op("EOR", Mode::Aby, 4, 1, true),
    /* 5A */ op("NOP", Mode::Imp, 2, 0, false),
    /* 5B */ op("SRE", Mode::Aby, 7, 0, false),
    /* 5C */ op("NOP", Mode::Abx, 4, 1, false),
    /* 5D */ op("EOR", Mode::Abx, 4, 1, true),
    /* 5E */ op("LSR", Mode::Abx, 7, 0, true),
    /* 5F */ op("SRE", Mode::Abx, 7, 0, false),
    /* 60 */ op("RTS", Mode::Imp, 6, 0, true),
    /* 61 */ op("ADC", Mode::Izx, 6, 0, true),
    /* 62 */ op("JAM", Mode::Imp, 0, 0, false),
    /* 63 */ op("RRA", Mode::Izx, 8, 0, false),
    /* 64 */ op("NOP", Mode::Zp0, 3, 0, false),
    /* 65 */ op("ADC", Mode::Zp0, 3, 0, true),
    /* 66 */ op("ROR", Mode::Zp0, 5, 0, true),
    /* 67 */ op("RRA", Mode::Zp0, 5, 0, false),
    /* 68 */ op("PLA", Mode::Imp, 4, 0, true),
    /* 69 */ op("ADC", Mode::Imm, 2, 0, true),
    /* 6A */ op("ROR", Mode::Acc, 2, 0, true),
    /* 6B */ op("ARR", Mode::Imm, 2, 0, false),
    /* 6C */ op("JMP", Mode::Ind, 5, 0, true),
    /* 6D */ op("ADC", Mode::Abs, 4, 0, true),
    /* 6E */ op("ROR", Mode::Abs, 6, 0, true),
    /* 6F */ op("RRA", Mode::Abs, 6, 0, false),
    /* 70 */ op("BVS", Mode::Rel, 2, 2, true),
    /* 71 */ op("ADC", Mode::Izy, 5, 1, true),
    /* 72 */ op("JAM", Mode::Imp, 0, 0, false),
    /* 73 */ op("RRA", Mode::Izy, 8, 0, false),
    /* 74 */ op("NOP", Mode::Zpx, 4, 0, false),
    /* 75 */ op("ADC", Mode::Zpx, 4, 0, true),
    /* 76 */ op("ROR", Mode::Zpx, 6, 0, true),
    /* 77 */ op("RRA", Mode::Zpx, 6, 0, false),
    /* 78 */ op("SEI", Mode::Imp, 2, 0, true),
    /* 79 */ op("ADC", Mode::Aby, 4, 1, true),
    /* 7A */ op("NOP", Mode::Imp, 2, 0, false),
    /* 7B */ op("RRA", Mode::Aby, 7, 0, false),
    /* 7C */ op("NOP", Mode::Abx, 4, 1, false),
    /* 7D */ op("ADC", Mode::Abx, 4, 1, true),
    /* 7E */ op("ROR", Mode::Abx, 7, 0, true),
    /* 7F */ op("RRA", Mode::Abx, 7, 0, false),
    /* 80 */ op("NOP", Mode::Imm, 2, 0, false),
    /* 81 */ op("STA", Mode::Izx, 6, 0, true),
    /* 82 */ op("NOP", Mode::Imm, 2, 0, false),
    /* 83 */ op("SAX", Mode::Izx, 6, 0, false),
    /* 84 */ op("STY", Mode::Zp0, 3, 0, true),
    /* 85 */ op("STA", Mode::Zp0, 3, 0, true),
    /* 86 */ op("STX", Mode::Zp0, 3, 0, true),
    /* 87 */ op("SAX", Mode::Zp0, 3, 0, false),
    /* 88 */ op("DEY", Mode::Imp, 2, 0, true),
    /* 89 */ op("NOP", Mode::Imm, 2, 0, false),
    /* 8A */ op("TXA", Mode::Imp, 2, 0, true),
    /* 8B */ op("XAA", Mode::Imm, 2, 0, false),
    /* 8C */ op("STY", Mode::Abs, 4, 0, true),
    /* 8D */ op("STA", Mode::Abs, 4, 0, true),
    /* 8E */ op("STX", Mode::Abs, 4, 0, true),
    /* 8F */ op("SAX", Mode::Abs, 4, 0, false),
    /* 90 */ op("BCC", Mode::Rel, 2, 2, true),
    /* 91 */ op("STA", Mode::Izy, 6, 0, true),
    /* 92 */ op("JAM", Mode::Imp, 0, 0, false),
    /* 93 */ op("AHX", Mode::Izy, 6, 0, false),
    /* 94 */ op("STY", Mode::Zpx, 4, 0, true),
    /* 95 */ op("STA", Mode::Zpx, 4, 0, true),
    /* 96 */ op("STX", Mode::Zpy, 4, 0, true),
    /* 97 */ op("SAX", Mode::Zpy, 4, 0, false),
    /* 98 */ op("TYA", Mode::Imp, 2, 0, true),
    /* 99 */ op("STA", Mode::Aby, 5, 0, true),
    /* 9A */ op("TXS", Mode::Imp, 2, 0, true),
    /* 9B */ op("TAS", Mode::Aby, 5, 0, false),
    /* 9C */ op("SHY", Mode::Abx, 5, 0, false),
    /* 9D */ op("STA", Mode::Abx, 5, 0, true),
    /* 9E */ op("SHX", Mode::Aby, 5, 0, false),
    /* 9F */ op("AHX", Mode::Aby, 5, 0, false),
    /* A0 */ op("LDY", Mode::Imm, 2, 0, true),
    /* A1 */ op("LDA", Mode::Izx, 6, 0, true),
    /* A2 */ op("LDX", Mode::Imm, 2, 0, true),
    /* A3 */ op("LAX", Mode::Izx, 6, 0, false),
    /* A4 */ op("LDY", Mode::Zp0, 3, 0, true),
    /* A5 */ op("LDA", Mode::Zp0, 3, 0, true),
    /* A6 */ op("LDX", Mode::Zp0, 3, 0, true),
    /* A7 */ op("LAX", Mode::Zp0, 3, 0, false),
    /* A8 */ op("TAY", Mode::Imp, 2, 0, true),
    /* A9 */ op("LDA", Mode::Imm, 2, 0, true),
    /* AA */ op("TAX", Mode::Imp, 2, 0, true),
    /* AB */ op("LXA", Mode::Imm, 2, 0, false),
    /* AC */ op("LDY", Mode::Abs, 4, 0, true),
    /* AD */ op("LDA", Mode::Abs, 4, 0, true),
    /* AE */ op("LDX", Mode::Abs, 4, 0, true),
    /* AF */ op("LAX", Mode::Abs, 4, 0, false),
    /* B0 */ op("BCS", Mode::Rel, 2, 2, true),
    /* B1 */ op("LDA", Mode::Izy, 5, 1, true),
    /* B2 */ op("JAM", Mode::Imp, 0, 0, false),
    /* B3 */ op("LAX", Mode::Izy, 5, 1, false),
    /* B4 */ op("LDY", Mode::Zpx, 4, 0, true),
    /* B5 */ op("LDA", Mode::Zpx, 4, 0, true),
    /* B6 */ op("LDX", Mode::Zpy, 4, 0, true),
    /* B7 */ op("LAX", Mode::Zpy, 4, 0, false),
    /* B8 */ op("CLV", Mode::Imp, 2, 0, true),
    /* B9 */ op("LDA", Mode::Aby, 4, 1, true),
    /* BA */ op("TSX", Mode::Imp, 2, 0, true),
    /* BB */ op("LAS", Mode::Aby, 4, 1, false),
    /* BC */ op("LDY", Mode::Abx, 4, 1, true),
    /* BD */ op("LDA", Mode::Abx, 4, 1, true),
    /* BE */ op("LDX", Mode::Aby, 4, 1, true),
    /* BF */ op("LAX", Mode::Aby, 4, 1, false),
    /* C0 */ op("CPY", Mode::Imm, 2, 0, true),
    /* C1 */ op("CMP", Mode::Izx, 6, 0, true),
    /* C2 */ op("NOP", Mode::Imm, 2, 0, false),
    /* C3 */ op("DCP", Mode::Izx, 8, 0, false),
    /* C4 */ op("CPY", Mode::Zp0, 3, 0, true),
    /* C5 */ op("CMP", Mode::Zp0, 3, 0, true),
    /* C6 */ op("DEC", Mode::Zp0, 5, 0, true),
    /* C7 */ op("DCP", Mode::Zp0, 5, 0, false),
    /* C8 */ op("INY", Mode::Imp, 2, 0, true),
    /* C9 */ op("CMP", Mode::Imm, 2, 0, true),
    /* CA */ op("DEX", Mode::Imp, 2, 0, true),
    /* CB */ op("AXS", Mode::Imm, 2, 0, false),
    /* CC */ op("CPY", Mode::Abs, 4, 0, true),
    /* CD */ op("CMP", Mode::Abs, 4, 0, true),
    /* CE */ op("DEC", Mode::Abs, 6, 0, true),
    /* CF */ op("DCP", Mode::Abs, 6, 0, false),
    /* D0 */ op("BNE", Mode::Rel, 2, 2, true),
    /* D1 */ op("CMP", Mode::Izy, 5, 1, true),
    /* D2 */ op("JAM", Mode::Imp, 0, 0, false),
    /* D3 */ op("DCP", Mode::Izy, 8, 0, false),
    /* D4 */ op("NOP", Mode::Zpx, 4, 0, false),
    /* D5 */ op("CMP", Mode::Zpx, 4, 0, true),
    /* D6 */ op("DEC", Mode::Zpx, 6, 0, true),
    /* D7 */ op("DCP", Mode::Zpx, 6, 0, false),
    /* D8 */ op("CLD", Mode::Imp, 2, 0, true),
    /* D9 */ op("CMP", Mode::Aby, 4, 1, true),
    /* DA */ op("NOP", Mode::Imp, 2, 0, false),
    /* DB */ op("DCP", Mode::Aby, 7, 0, false),
    /* DC */ op("NOP", Mode::Abx, 4, 1, false),
    /* DD */ op("CMP", Mode::Abx, 4, 1, true),
    /* DE */ op("DEC", Mode::Abx, 7, 0, true),
    /* DF */ op("DCP", Mode::Abx, 7, 0, false),
    /* E0 */ op("CPX", Mode::Imm, 2, 0, true),
    /* E1 */ op("SBC", Mode::Izx, 6, 0, true),
    /* E2 */ op("NOP", Mode::Imm, 2, 0, false),
    /* E3 */ op("ISB", Mode::Izx, 8, 0, false),
    /* E4 */ op("CPX", Mode::Zp0, 3, 0, true),
    /* E5 */ op("SBC", Mode::Zp0, 3, 0, true),
    /* E6 */ op("INC", Mode::Zp0, 5, 0, true),
    /* E7 */ op("ISB", Mode::Zp0, 5, 0, false),
    /* E8 */ op("INX", Mode::Imp, 2, 0, true),
    /* E9 */ op("SBC", Mode::Imm, 2, 0, true),
    /* EA */ op("NOP", Mode::Imp, 2, 0, true),
    /* EB */ op("SBC", Mode::Imm, 2, 0, false),
    /* EC */ op("CPX", Mode::Abs, 4, 0, true),
    /* ED */ op("SBC", Mode::Abs, 4, 0, true),
    /* EE */ op("INC", Mode::Abs, 6, 0, true),
    /* EF */ op("ISB", Mode::Abs, 6, 0, false),
    /* F0 */ op("BEQ", Mode::Rel, 2, 2, true),
    /* F1 */ op("SBC", Mode::Izy, 5, 1, true),
    /* F2 */ op("JAM", Mode::Imp, 0, 0, false),
    /* F3 */ op("ISB", Mode::Izy, 8, 0, false),
    /* F4 */ op("NOP", Mode::Zpx, 4, 0, false),
    /* F5 */ op("SBC", Mode::Zpx, 4, 0, true),
    /* F6 */ op("INC", Mode::Zpx, 6, 0, true),
    /* F7 */ op("ISB", Mode::Zpx, 6, 0, false),
    /* F8 */ op("SED", Mode::Imp, 2, 0, true),
    /* F9 */ op("SBC", Mode::Aby, 4, 1, true),
    /* FA */ op("NOP", Mode::Imp, 2, 0, false),
    /* FB */ op("ISB", Mode::Aby, 7, 0, false),
    /* FC */ op("NOP", Mode::Abx, 4, 1, false),
    /* FD */ op("SBC", Mode::Abx, 4, 1, true),
    /* FE */ op("INC", Mode::Abx, 7, 0, true),
    /* FF */ op("ISB", Mode::Abx, 7, 0, false),
];
